BLUFACTIONWEAPONS = "NATO";
BLUFACTIONSCOPES  = 2;
BLUFACTIONNVG	  = 1;
BLUFACTIONBARREL  = 2;
BLUFACTIONMUZZLE  = 1;
BLUFACTIONGPS     = 1;

OP4FACTIONWEAPONS = "CSAT";
OP4FACTIONSCOPES  = 2;
OP4FACTIONNVG	  = 1;
OP4FACTIONBARREL  = 2;
OP4FACTIONMUZZLE  = 1;
OP4FACTIONGPS     = 1;


INDFACTIONWEAPONS = "AAF";
INDFACTIONSCOPES  = 2;
INDFACTIONNVG	  = 1;
INDFACTIONBARREL  = 2;
INDFACTIONMUZZLE  = 1;
INDFACTIONGPS     = 1;
